# This is a basic workflow to help you get started with Actions

name: sql-build-deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildDeploy:
    # The type of runner that the job will run on
    runs-on: [self-hosted]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup msbuild
        uses: microsoft/setup-msbuild@v1

      # where are we?
      - name: where are we
        run: dir

      # build the sql project 
      - name: build the sqlproj
        run: |
          msbuild.exe .\Adventureworksproject\Database1\Database1.sqlproj /p:DeployOnBuild=true 

      # deploy the DACPAC
      - name: Deploy database updates
        #working-directory: c:\program files\Microsoft SQL Server\150\DAC\bin\
        run: c:\DAC\bin\sqlpackage.exe /Action:Publish /SourceFile:".\Adventureworksproject\Database1\bin\Debug\Database1.dacpac" /TargetDatabaseName:AdventureWorks2019 /TargetServerName:"ghselfhost-vm" /TargetUser:"forpipeline" /TargetPassword:"abc123"
