# build and deploy a dacpac to a target database

name: sql-build-deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  buildDeploy:
  
    # use a self-hosted windows runner
    runs-on: [self-hosted, windows, x64]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # this step adds the msbuild path into the gh workflow context
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v1

      # for debugging, take a look at where we are in the file system
      - name: where are we
        run: dir

      # build the sql project 
      - name: build the sqlproj
        run: |
          msbuild.exe .\Adventureworksproject\Database1\Database1.sqlproj /p:DeployOnBuild=true 

      # deploy the DACPAC
      - name: Deploy database updates
        run: c:\DAC\bin\sqlpackage.exe /Action:Publish /SourceFile:".\Adventureworksproject\Database1\bin\Debug\Database1.dacpac" /TargetDatabaseName:AdventureWorks2019 /TargetServerName:"ghselfhost-vm" /TargetUser:"forpipeline" /TargetPassword:${{ secrets.DB_PWD}}
